# Generated by Django 5.2.1 on 2025-05-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_reward", models.BooleanField(default=False)),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1, help_text="Периодичность в днях (1–7)"
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Время на выполнение в секундах"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_reward": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
